### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by udoprog** [steveklabnik/semver#127]
Hey,

I was pretty unlucky to get [my change][fb6e6338e5e8f75e96ee6cdb60763197fc1c16a5] merged immediately after the 0.8 release. But I would really appreciate having a version on crates with that feature.

Could you do another release?

Thanks!

**Comment by steveklabnik** [comment]
`semver` is part of the libz blitz, and so I was going to wait until those reviews came in to do them and cut a new release then. It's taking a while though, so yeah, maybe I can. Sorry about that!

**Comment by steveklabnik** [comment]
published as 0.9.0, thanks!
