### ISSUE TITLE
Use `?` instead of `unwrap` in examples

### ISSUE THREAD

**Issue by KodrAus** [steveklabnik/semver#129]
[Relevant API guidelines](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-question-mark)

Replace uses of `.unwrap` in examples with `?` so they're a bit more idiomatic. Have a look at the API guideline examples for some ideas on how to do this.

**Comment by jansol** [comment]
I'm interested in working on this

**Comment by jansol** [comment]
...or not, it seems.

**Comment by KodrAus** [comment]
Oh sorry about that @jansol! Are there any other issues here you'd be interested in taking on?

**Comment by jansol** [comment]
No problem. Nothing has caught my eye yet, but I haven't looked very thoroughly yet.

**Comment by anna-liao** [comment]
oh woops, just noticed that it's in progress at https://github.com/steveklabnik/semver/pull/144 Will look for something else :)

**Comment by KodrAus** [comment]
@anna-liao No problem! There are plenty of other issues here and in [`semver-parser`](https://github.com/steveklabnik/semver-parser/issues) too. If you can't find anything you like the look of also feel free to reach out on [gitter](https://gitter.im/rust-impl-period/WG-libz-blitz).

**Comment by apopiak** [comment]
#160 resolves this, correct?
