### ISSUE TITLE
Add keywords and categories to Cargo.toml

### ISSUE THREAD

**Issue by KodrAus** [steveklabnik/semver#133]
[Relevant API guidelines](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-metadata)

Add the following properties to the `Cargo.toml`:

- `keywords`
- `categories`

What categories does `semver` fit in best?

**Comment by muzikmoe** [comment]
I have searched some keywords in crates.io, some crates provide semver-like function: 
* [check-verions](https://crates.io/crates/check-versions)
  - keywords: `version`
  - categories: `Development tools` `Rust patterns`
* [deb-version](https://crates.io/crates/deb-version)
  - keywords: `None`
  - categories: `Parsing` `Operating systems`
* [rn](https://crates.io/crates/rn)
  - keywords: `cli` `utility` `...`
  - categories: `Development tools`

so for semver, my basic choice is(there may be more choice):
keywords: `version`
categories: `Development tools`

**Comment by KodrAus** [comment]
Thanks for investigating @muzikmoe! We could probably add a few more keywords in there. Maybe `version`, `semantic`, `compare`. We could probably also add `Parsing` to the categories, since one of the crate's primary functions to parse semantic versions (the fact that it defers to `semver_parser` isn't so important).
