### ISSUE TITLE
Add html_root_url attribute to crate root

### ISSUE THREAD

**Issue by KodrAus** [steveklabnik/semver#134]
[Relevant API guidelines](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-html-root)

Add the `html_root_url` attribute to the `lib.rs` file that points to `"https://docs.rs/semver/MAJOR.MINOR.PATCH"`. Also add a note to the `Cargo.toml` to remember to update this value when publishing a new version of the crate.

If we're expecting the next release to be `1.0.0` then we can probably just put that version in the `html_root_url` attribute.

**Comment by stanciuadrian** [comment]
I'll patch this. Should I indicate `0.9.0` or `1.0.0` ?

**Comment by KodrAus** [comment]
Hi @stanciuadrian we've got an open PR for this in #140.

But there is an issue to add this attribute in the `semver_parser` crate if you'd like to take that on: https://github.com/steveklabnik/semver-parser/issues/19

**Comment by stanciuadrian** [comment]
Missed that! Thanks for letting me know. I'll take it.

**Comment by opilar** [comment]
We can close this because of #149
