### ISSUE TITLE
Support padding in `Display`.

### ISSUE THREAD

**Issue by dpc** [steveklabnik/semver#187]
```
fn main() {
    let v = semver::Version::from((0, 0, 0));
    println!("{:<15} {:<15}", v, v);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e68ff1fc17bf96e41963222800080d09

Results in:

```
0.0.0 0.0.0
```

I'm printing `Version` in a tabular fashion, and it would help a lot if this was supported.

**Comment by rossmacarthur** [comment]
Looks like this is supported now.

**Comment by dpc** [comment]
Have not verified, but I'm fine with closing the issue. Thanks!
