### ISSUE TITLE
Diesel feature missing from crates.io

### ISSUE THREAD

**Issue by 0x1793d1** [steveklabnik/semver#194]
Hi,

I'd like to use Version as a diesel type thanks to the diesel feature, but it seems to be missing from crates.io.

Can anyone help me?

Thanks

**Comment by steveklabnik** [comment]
I haven't put out a release yet; if you'd like to use it, you can use semver from the git repo like this: https://github.com/rust-lang/crates.io/blob/master/Cargo.toml#L35

I have had some plans to get out a release for a while, but haven't had as much time lately. I'll get there!
