### ISSUE TITLE
This crate considers 0.2.4 to be SemVer compatible with 0.2.3, but it isn't

### ISSUE THREAD

**Issue by p-e-w** [steveklabnik/semver#198]
As stated in its README, this crate interprets `^0.2.3` to mean `>=0.2.3 <0.3.0`. In other words, it assumes that patch releases have a compatible public API even if the major version is 0. For example, it assumes that version 0.2.4 is compatible with version 0.2.3.

Unfortunately, the SemVer specification says no such thing. In fact, [it says the exact opposite](https://semver.org/spec/v2.0.0.html#spec-item-4) (emphasis mine):

> 4. Major version zero (0.y.z) is for initial development. **Anything MAY change at any time.** The public API SHOULD NOT be considered stable.
>
> 5. Version 1.0.0 defines the public API. The way in which the version number is incremented **after this release** is dependent on this public API and how it changes.
>
> 6. Patch version Z (x.y.Z | **x > 0**) MUST be incremented if [...]
>
> 7. Minor version Y (x.Y.z | **x > 0**) MUST be incremented if [...]
>
> 8. Major version X (X.y.z | **X > 0**) MUST be incremented if [...]

The spec is crystal clear: Anything goes while the major version is zero. Prior to 1.0.0, SemVer provides no compatibility guarantees whatsoever, *even for patch releases.* Obviously, this is not how most crates do versioning in reality, and breaking the world between 0.2.3 and 0.2.4 would be considered bad practice by most people. But the fact is that SemVer absolutely allows for this to happen, so this crate should not consider any pre-1.0.0 version to be compatible with any other.

This is not just a theoretical concern. I just got bitten by a crate that changed its API in a pre-1.0.0 patch release. I was ready to file an issue with that crate but decided to check what SemVer actually says one more time just to be sure. Turns out that the maintainer is perfectly within the rules of SemVer (perhaps not in spirit, but certainly in letter), and it is Cargo that's at fault for performing an unsafe version bump – and, by extension, this crate.

**Comment by steveklabnik** [comment]
Hi,

While the spec does say this, this is not how the semantics of `^` are determined. The matchers are not in the semver spec at all. This crate implements `^` the same way that all of the other implementations do. So thank you for the report, but this is not a bug!

(Additionally, we (as in, the maintainers of the semver spec, of which I'm one) are planning on specifying ranges in the spec itself, as well as cleaning up the language here.)

**Comment by p-e-w** [comment]
> While the spec does say this, this is not how the semantics of ^ are determined.

Huh? The README states that "Caret requirements allow SemVer compatible updates to a specified version". Currently, that is simply false, since 0.2.4 is not SemVer compatible with 0.2.3 according to SemVer 2.0.0.

I honestly see a huge problem here. Everyone is telling everyone else to use Semantic Versioning everywhere. Breaking compatibility between 0.2.3 and 0.2.4 is perfectly fine in Semantic Versioning, yet releasing a crate which does this breaks the world.
