### ISSUE TITLE
0.10.0 published to crates.io but not pushed here to github

### ISSUE THREAD

**Issue by Arnavion** [steveklabnik/semver#210]
Hello, I believe you published https://crates.io/crates/semver/0.10.0 but this repository's master is still at 0.9.0 (still at 2a9e42b3864a0628a08374c7fa410711e1bec2fe ). Could you `git push` the 0.10.0 commits and tag?

**Comment by steveklabnik** [comment]
Hmm, I am actually a bit confused; I don't remember publishing 0.10.0. I am gonna have to inspect what it looks like and figure it out... Thank you for drawing this to my attention! Seems... bad.

**Comment by Arnavion** [comment]
I see. I did actually worry about it being hacked or changed ownership, etc, so I checked the crates.io API, and [it does seem to say it was published by you.](https://crates.io/api/v1/crates/semver/0.10.0)

I also did a diff of this repo's master and the crate tarball, and the only difference is that the crate tarball has Windows newlines and the one line in the Cargo.toml to change the version number.

```sh
curl -L https://crates.io/api/v1/crates/semver/0.10.0/download | tar fx -
(cd semver-0.10.0 && find -type f | xargs dos2unix && mv Cargo.toml.orig Cargo.toml)

git clone ssh://github.com/steveklabnik/semver
(cd semver && rm -rf .git)

diff -urpN semver semver-0.10.0 | less
```

```patch
iff -urpN semver/Cargo.toml semver-0.10.0/Cargo.toml
--- semver/Cargo.toml   2020-07-23 10:34:44.291521349 -0700
+++ semver-0.10.0/Cargo.toml    2020-07-23 10:35:21.268703082 -0700
@@ -1,7 +1,7 @@
 [package]

 name = "semver"
-version = "0.9.0"
+version = "0.10.0"
 authors = ["Steve Klabnik <steve@steveklabnik.com>", "The Rust Project Developers"]
 license = "MIT/Apache-2.0"
 repository = "https://github.com/steveklabnik/semver"
diff -urpN semver/.cargo_vcs_info.json semver-0.10.0/.cargo_vcs_info.json
--- semver/.cargo_vcs_info.json 1969-12-31 16:00:00.000000000 -0800
+++ semver-0.10.0/.cargo_vcs_info.json  2020-07-23 10:35:21.264702955 -0700
@@ -0,0 +1,5 @@
+{
+  "git": {
+    "sha1": "5201b0c4cf9c9219167997955d6168406bd62e79"
+  }
+}
```

That's why I thought you'd simply forgotten to `git push` the commits and opened this issue.

**Comment by Arnavion** [comment]
Also, the publish date is right after when you merged a bunch of PRs and made a bunch of other commits. The last commit in master is 2020-05-25T03:27:08Z and the publish date in the crates.io API is 2020-05-25T03:30:56.926240+00:00

**Comment by steveklabnik** [comment]
Hm. Thanks for the investigation! I had a *lot* going on in this time period, so that's probably the deal... I was going to look at the computer I was using then to double check everything, but at least it was actually me and I'm just forgetful.

**Comment by steveklabnik** [comment]
okay pushed as https://github.com/steveklabnik/semver/commit/db822b7fc20fd3bbdac742ac8eec82162df98257 and https://github.com/steveklabnik/semver/releases/tag/v0.10.0

thanks / sorry!
