### ISSUE TITLE
Fix up doc urls and such

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/semver#50]
Now that this has been transferred, I will need to ensure all URLs and upload tokens work

**Comment by filsmick** [comment]
The [documentation](https://doc.rust-lang.org/semver) link is still broken as of writing.

**Comment by steveklabnik** [comment]
Yeah, I haven't still O_O. Sorry :( will do soon.

**Comment by steveklabnik** [comment]
![2015-10-21-174052_793x83_scrot](https://cloud.githubusercontent.com/assets/27786/10651006/d6a1ec76-781a-11e5-860a-b9a6e9c19bfd.png)


:100:

**Comment by steveklabnik** [comment]
Oh, I still have to deploy a new version to get crates.io to update. Let me make sure that we're okay with that, and I'll push.

**Comment by steveklabnik** [comment]
Published v0.2.0
