### ISSUE TITLE
Implement comparison rules for pre-release tags

### ISSUE THREAD

**Issue by mbrubeck** [steveklabnik/semver#53]
The comparison functions in `version_req.rs` currently ignore prerelease tags.  They should instead follow the [NPM rules for prerelease tags](https://docs.npmjs.com/misc/semver#prerelease-tags):

> If a version has a prerelease tag (for example, `1.2.3-alpha.3`) then it will only be allowed to satisfy comparator sets if at least one comparator with the same `[major, minor, patch]` tuple also has a prerelease tag.

**Comment by steveklabnik** [comment]
Re-opening since #71 landed

**Comment by steveklabnik** [comment]
Fixed by https://github.com/steveklabnik/semver/pull/72
