### ISSUE TITLE
<= X parsed as X

### ISSUE THREAD

**Issue by bluss** [steveklabnik/semver#80]
I was trying this in cargo: `>= 0.1, <= 0.2`. It's not valid syntax, but it is accepted without error. Output suggests it was interpreted as `>= 0.1, 0.2`.

(`>= 0.1, < 0.3` ended up being what I wanted).

**Comment by steveklabnik** [comment]
>  It's not valid syntax,

What's not valid about this?

**Comment by bluss** [comment]
Not sure why I said that, maybe because the `<=` operator was not listed in crates.io docs. http://doc.crates.io/specifying-dependencies.html

It seems like the version spec in the issue is working as indended when I try it now, maybe this was a mistake.

**Comment by steveklabnik** [comment]
Okay! I'm gonna just give this a close then.
