### ISSUE TITLE
Clarify version requirement rules

### ISSUE THREAD

**Issue by dhardy** [steveklabnik/semver#81]

**Comment by dhardy** [comment]
Semver appears to derive requirements rules from [npm's semver](https://docs.npmjs.com/misc/semver). This specifies 

>   = Equal. If no operator is specified, then equality is assumed, so this operator is optional, but MAY be included.

However, your version of semver appears to consider a requirement string without a prefixed operator equivalent to prefixing a carot: `1.2.3 == ^1.2.3`.

Could you please clarify whether this is an intentional deviation, and if so mention it in the readme?

**Comment by dhardy** [comment]
I see some further deviations:

Ranges appear to be written with a comma: `let r = req("> 0.0.9, <= 2.5.3");`, where npm doesn't require a comma: `>=1.2.7 <1.3.0`.

NPM allows hypen-ranges (`1.2 - 2.3.4`) and logical-or (`||`)

This semver appears to allow lists of alternatives separated by comma, although unintuitive and probably useless since all rules must match: `0.1.0, 0.1.4, 0.1.6`.

**Comment by steveklabnik** [comment]
> Could you please clarify whether this is an intentional deviation, and if so mention it in the readme?

It is for now, but it's not clear if it will be in this library or in Cargo itself before 1.0.

Your other cases are covered by open issues, like https://github.com/steveklabnik/semver/issues/55 https://github.com/steveklabnik/semver/issues/57 and https://github.com/steveklabnik/semver/issues/56

**Comment by dhardy** [comment]
So the rules will not change from the point of view of Cargo but it's not clear what will happen to this library?

The issue I want to fix is the [documentation in Cargo](https://github.com/rust-lang/cargo/issues/1418). It sounds like Cargo should not refer to semver documentation but be self-contained then?

**Comment by dhardy** [comment]
To repeat my question: So the rules will not change from the point of view of Cargo?

**Comment by steveklabnik** [comment]
There has been significant opposition to changing them, and so I'm not sure if they'll end up changed or not.

**Comment by Dragonrun1** [comment]
Better to fix things now to follow the SemVer rules then to be the odd ball that no one wants to work with. Also might be better to go to the source of the rules http://semver.org/ instead of just looking at how someone else implemented it possible wrongly as well. I've notice npm has some things that don't seem to be right either in the way they do things.

**Comment by steveklabnik** [comment]
> Better to fix things now to follow the SemVer rules

The SemVer spec does not describe these operators, so their behavior is always defined by various implementations.

> then to be the odd ball that no one wants to work with.

At least one other ecosystem uses the rules we're using.

**Comment by steveklabnik** [comment]
This is all staying as-is; for 1.0 this will be well documented, but since the question is answered, I'm closing the issue. Thanks!
